#!/system/bin/sh
# Volume Steps+ for Magisk 20+
# Original source by: veez21 @xda-developers 
# Remake and Upgrade by: WilomanCZ
# Maintained by peterroth, 2020


# Default Variables
div="=================================";
MODDIR="/data/adb/modules/VolumeStepsPlus";
MODDIR2=$MODDIR/system/xbin;
scfile=$MODDIR2/mediasteps;
prop=$MODDIR/system.prop;

# Functions
get_file_prop() {
_prop=$2
_prop=$(grep "$1=" $_prop)
val=${_prop#*=}
echo $val
unset _prop
}

set_file_prop() {
_prop=$3
sed -i "s/${1}=.*/${1}=${2}/g" $_prop
unset _prop
}

# Extra Variables
SCRN="Media volume steps";

# Main
clear;

current=$(getprop ro.config.media_vol_steps);
applied=$(get_file_prop ro.config.media_vol_steps ${prop});

echo $div;
echo "Increase $SCRN";
echo $div;
echo "";
echo "Current value: $current";

if [ "$current" -ne "$applied" ]; then
	echo "To be applied: $applied" ;
	echo "NOTE: REBOOT TO APPLY CHANGES";
fi 

echo $div;
echo "";
echo -n "Write number of steps count (q for exit): ";
read volume

if [ "$volume" == "$applied" ]; then
	echo "Already entered";
	exit;
elif [ "$volume" == "q" ] || [ "$volume" == "Q" ]; then
clear;
	echo "Exit";
	sleep 1;
	exit;

elif [ "$volume" == "" ] || [ -n "$(echo $volume | tr -d '0-9')" ]; then
	echo "Number only! Try it again.";
	sleep 2;
	sh $scfile
	exit;
else
	echo "Changing to: ${volume}";
	sleep 1;
set_file_prop ro.config.media_vol_steps ${volume} $prop;
	echo "Reboot device to apply changes.";
	echo -n "Do you want reboot device now? (y/n) or empty is NO: " ;
	read reb
	   if [ "$reb" == "y" ] || [ "$reb" == "Y" ]; then
	reboot;
	  elif [ "$reb" == "" ] || [ "$reb" == "n" ] || [ "$reb" == "N" ]; then
	exit ;
fi 
	exit;
fi